// <auto-generated />
using System;
using L06HandsOn.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace L06HandsOn.Migrations
{
    [DbContext(typeof(AliensContext))]
    partial class AliensContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("L06HandsOn.Models.Alien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Arms")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Head")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Legs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlanetOfOrigin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Aliens");
                });
#pragma warning restore 612, 618
        }
    }
}
